### ISSUE TITLE
How to use rust-imap with socks proxy ?

### ISSUE THREAD

**Issue by Riduidel** [jonhoo/rust-imap#108]
I know rust is fairly low-level programming language, so I guess I'll have to do some special code.

But

I'm writing an [rss to imap](https://github.com/Riduidel/rrss2imap) command-line tool which obviously use your crate (thanks, by the way).
I want to use this tool in corporate environment (with an enterprise proxy), where access to the free web is provided through a socks proxy I maintain to my home server.

How can I configure rust-imap to use my socks proxy ? Should I use rust-socks ? Or is it possible to configure rust (through an environment variable, as an example) to use that socks proxy ?

**Comment by jonhoo** [comment]
I haven't actually used a SOCKS proxy internally in a Rust program yet, so I'm not entirely sure, but [`imap::Cient::new`](https://docs.rs/imap/0.10.0/imap/struct.Client.html#method.new) allows you to construct an IMAP client over any type that is `Read + Write`, so as long as you have a way to establish the connection to the server, in whatever way you see fit, you should be able to use `imap` on top of that :)

**Comment by Riduidel** [comment]
Being a Rust beginner, I would love to have some help on that subject ;-)

**Comment by jonhoo** [comment]
My guess would be that you'll have to connect through the SOCKS proxy with something like [`socks::Socks5Stream`](https://docs.rs/socks/0.3.2/socks/struct.Socks5Stream.html). That'll give you back a `Socks5Stream`, which you can then pass to `Client::new`. You can then use `Client::secure` if you want to upgrade that connection to be a TLS secure connection, or just use `Client::login` to log in normally.
