### ISSUE TITLE
Support BODYSTRUCTURE parsing for FETCH results

### ISSUE THREAD

**Issue by lberezy** [jonhoo/rust-imap#116]
I think this might rely on the underlying parser crate supporting this (https://github.com/djc/imap-proto/issues/15), but it would be nice if this crate could expose a parsed BODYSTRUCTURE for messages (FETCH results).

This would be useful to allow the client to determine properties of a message in a bandwidth-constrained environment. Currently, the a message with large attachments must be fully downloaded and parsed just to determine that there are attachments.

**Comment by lberezy** [comment]
Just as an update, there's currently a pending pull request for https://github.com/djc/tokio-imap/pull/44 to support the parsing of BODYSTRUCTURE. This should make it fairly straight forward to expose this functionality in this crate, perhaps as an `Option<Bodystructure>` for Fetch results. Any thoughts?

**Comment by jonhoo** [comment]
Seems reasonable to me!

**Comment by JoshMcguigan** [comment]
I believe this functionality was merged in tokio-imap with https://github.com/djc/tokio-imap/pull/48.

**Comment by jonhoo** [comment]
Hmm, I _think_ we could have closed this once https://github.com/jonhoo/rust-imap/pull/150 landed, unless I'm missing something?

**Comment by JoshMcguigan** [comment]
Ah, yes I'd think so :+1:
