### ISSUE TITLE
IMAP server gives FLAGS response to FETCH

### ISSUE THREAD

**Issue by NickeZ** [jonhoo/rust-imap#117]
Hi,

I'm writing a simple tool to dump all my e-mail in an mbox. 

The IMAP server seems to send `* FLAGS` twice but I cannot tell for sure what is going on because I'm not sure where to exactly add the log statements so that I can see every single packet to and from the server. I suppose either there is an extra line at the end of the "EXAMINE" response, or there is an extra line at the beginning of the "FETCH" response.

The first time I do `fetch()` after `examine()` I get the below panic:

```
Thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse(Unexpected("MailboxData(Flags([\"\\\\Answered\", \"\\\\Deleted\", \"\\\\Draft\", \"\\\\Flagged\", \"
\\\\Seen\",...
```

After patching `rust-imap` with the changes below I can run more "fetches" and I see that it is only the first time I get unsolicited data.

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 87249d0..3fe0326 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -66,6 +66,8 @@ extern crate imap_proto;
 extern crate native_tls;
 extern crate nom;
 extern crate regex;
+#[macro_use]
+extern crate log;

 mod parse;

diff --git a/src/parse.rs b/src/parse.rs
index c89aa6d..021eee4 100644
--- a/src/parse.rs
+++ b/src/parse.rs
@@ -113,10 +113,22 @@ pub fn parse_fetches(
             }

             Ok(MapOrNot::Map(fetch))
-        }
+        },
+        Response::MailboxData(m) => {
+            use imap_proto::MailboxDatum;
+            match m {
+                MailboxDatum::Flags(flags) => {
+                    trace!("Matched flags")
+                },
+                _ => {}
+            }
+            Ok(MapOrNot::Ignore)
+        },
         resp => Ok(MapOrNot::Not(resp)),
     };

     unsafe { parse_many(lines, f, unsolicited) }
 }
```

1. What do you think is the proper solution here?
2. It would  be great to be able to trace the "imap conversation" to debug these kinds of issues.

Sorry if this doesn't make any sense, I'm new to IMAP.

**Comment by jonhoo** [comment]
Ah, there's a hidden `debug` field on `Connection`, which you can get at through the `Deref` that is implemented on `Client` and `Session`:
https://github.com/jonhoo/rust-imap/blob/ba09886e3b12867926093faf61711351ca5d2a59/src/client.rs#L78

Try setting that to `true`?

As for the issue you are experiencing, it's hard to say what's going on without seeing the trace. In general, `parse_fetches` should only be called in contexts where only `FETCH` responses can be returned. In this case, it looks like you are also getting `MailboxData::Flags` responses, which doesn't seem right. Maybe `EXAMINE` can return `Flags` as well? I know @Emm54321 has worked a bunch on unsolicited server responses in the context of #114, so maybe they can shed some light on this?

**Comment by NickeZ** [comment]
After coding some more I saw that I got the same issue if I ran `LIST` after `EXAMINE`. So it seems like the response to `EXAMINE` actually gives the `* FLAGS` twice.. I'll try the debug flag and see if I can get a better idea of the problem.

**Comment by jonhoo** [comment]
@NickeZ I know this is late follow-up, but did you ever figure out what was wrong here?

**Comment by NickeZ** [comment]
hey! I don't remember really. I think I managed to dump all my e-mail. But I don't recall if this was a problem in the end. Thanks!

**Comment by jonhoo** [comment]
Thanks for following up! Well, I think in that case we can close this, and if someone runs into it again, re-open :)
