### ISSUE TITLE
How to cancel an idle connection

### ISSUE THREAD

**Issue by dignifiedquire** [jonhoo/rust-imap#121]
I need to support the following API

- on one thread a connection is made, and switched to `idle` using `wait`
- when shutting down gracefully, another thread needs to send a signal to interrupt the `idle` and shutting down the connection. 

Is this possible with the current api and I am missing something, or is there something that needs to be added?

**Comment by jonhoo** [comment]
Hmm, that's a little tricky to do, but I think it may be possible. Specifically, if you are on a Unix system, you should be able to establish the connection yourself first (using `std::net:TcpStream::connect`), get another handle to the same connection with [`try_clone`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.try_clone), create an `imap::Client` from the first handle with [`new`](https://docs.rs/imap/1/imap/struct.Client.html#method.new), and then terminate the connection using that second handle from the other thread when appropriate.

**Comment by dignifiedquire** [comment]
Thanks, started looking into this, and it almost works, but `read_greeting` is private currently, so I can't fully establish the connection. Any chance that could be switched to be public?

**Comment by jonhoo** [comment]
Hmm, why do you need `read_greeting` to be public? Is [`Client::login`](https://docs.rs/imap/1.0.1/imap/struct.Client.html#method.login) not sufficient?

**Comment by dignifiedquire** [comment]
When I am using my own stream I can not use `connect` or `connect_insecure`, which call the read_greeting. I do call `login` afterwards, but I thought the greeting reading would be still needed

**Comment by jonhoo** [comment]
You should be able to do `Client::new(stream).login` though, no?

**Comment by dignifiedquire** [comment]
yes that works 👌
