### ISSUE TITLE
Does idle.wait_keepalive actually reconnect?

### ISSUE THREAD

**Issue by dignifiedquire** [jonhoo/rust-imap#122]
The docs for `wait_keepalive` say that it does a reconnection after the timeout, but the implementation simply calls `wait_timeout` which, does not do any reconnection work. 

Am I missing something? 

Ref: https://github.com/jonhoo/rust-imap/blob/master/src/extensions/idle.rs#L124

**Comment by jonhoo** [comment]
Ah, the implication of "refresh the connection" was not intended to be that it reconnects, just that it periodically sends pings to the server to keep the connection alive. How do you think it should be phrased instead?

**Comment by dignifiedquire** [comment]
I think the phrasing is actually fine, now that I understand more about idle connections :D
