### ISSUE TITLE
Move from ZeroCopy to the rental crate

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/rust-imap#125]
The `imap::ZeroCopy` struct is effectively an implementation of the "rental pattern", which already has a good [crate implementation](https://docs.rs/rental/). It would be good to switch to the `rental` crate, but it would also constitute a breaking change, as `rental` creates a separate struct for each wrapped type.

**Comment by jonhoo** [comment]
Alternatively I wonder if we could use the [`zerocopy` crate](https://crates.io/crates/zerocopy).

**Comment by avitex** [comment]
How about the [`owning_ref` crate](https://github.com/Kimundi/owning-ref-rs)? The rental crate author recommends moving away from his, and the `zerocopy` crate is in google source

**Comment by jonhoo** [comment]
I think `owning_ref` might be harder to fit this use-case to if I remember correctly from last time I used it, but by all means, if you can get it to work, that'd be awesome!

**Comment by avitex** [comment]
The owner of `owning_ref` has kindly given control to me, so I can make a few changes.
I ran into a problem myself when I tried to use it, but should be able to resolve it soon enough :)

**Comment by dario23** [comment]
[async-imap](https://github.com/async-email/async-imap), a fork of this repo, has introduced rental in their code, maybe we could apply some of the same refactorings here?
