### ISSUE TITLE
Self Signed Certificates

### ISSUE THREAD

**Issue by abbgrade** [jonhoo/rust-imap#126]
Hello,

please excuse me, if this is a absolute beginner question, but how do i connect to servers with self signed certificates? It would be nice to disable the root certificate check and maybe do certificate pinning.

Thanks
Steffen

**Comment by jonhoo** [comment]
Hi!

This library uses [`native-tls`](https://github.com/sfackler/rust-native-tls) for its TLS, so you'd have to check how to do that within that library. Ultimately you'll end up with a `native_tls::TlsConnector`, and you just pass that to `imap::Client::secure`, and then it should work correctly :)

**Comment by abbgrade** [comment]
Thank you. I thought it happens in the `connect` function.

For the next guy who wants to know:

    let accept_invalid_certs = true;
    let tls = native_tls::TlsConnector::builder()
        .danger_accept_invalid_certs(accept_invalid_certs)
        .build()
        .unwrap();

**Comment by dario23** [comment]
> Thank you. I thought it happens in the `connect` function.
> 
> For the next guy who wants to know:
> 
> ```
> let accept_invalid_certs = true;
> let tls = native_tls::TlsConnector::builder()
>     .danger_accept_invalid_certs(accept_invalid_certs)
>     .build()
>     .unwrap();
> ```

**WARNING**: that one is the "closing your eyes and ignoring everything"-solution

what i think jonhoo was getting at was probably something using  [TlsConnectorBuilder::add_root_certificate](https://docs.rs/native-tls/0.2.3/native_tls/struct.TlsConnectorBuilder.html#method.add_root_certificate), where you specifically add (the root certificate for) the one certificate you generated (and self-signed), but keep the whole certificate-checking-machinery in place.
