### ISSUE TITLE
Asynchronous?

### ISSUE THREAD

**Issue by Boiethios** [jonhoo/rust-imap#127]
Is there any plan to pass the crate in full async since the `Future` trait is now stable?

**Comment by jonhoo** [comment]
Hi! I don't have any plans to move this crate to be asynchronous in the short term. For that, there's @djc's [`tokio-imap`](https://crates.io/crates/tokio-imap). Maybe one day if I end up with copious amounts of spare time :sweat_smile:

**Comment by djc** [comment]
@Boiethios if you need features from tokio-imap that are currently not supported, feel free to open an issue there to discuss. (That said, AFAICT the tokio ecosystem will only release a std::future-enabled version after async/await also go stable, so I'm not sure tokio-imap will move much before that happens.)

**Comment by Boiethios** [comment]
> Hi! I don't have any plans to move this crate to be asynchronous in the short term. For that, there's @djc's [`tokio-imap`](https://crates.io/crates/tokio-imap). Maybe one day if I end up with copious amounts of spare time 😅

> @Boiethios if you need features from tokio-imap that are currently not supported, feel free to open an issue there to discuss. (That said, AFAICT the tokio ecosystem will only release a std::future-enabled version after async/await also go stable, so I'm not sure tokio-imap will move much before that happens.)

Thanks for your answer. I will try `tokio-imap`, but I have the feeling that it is much lower level than  `imap` (maybe I am wrong, though).

**Comment by djc** [comment]
It probably is, but if you have a concrete use case we can certainly discuss how to make the API more pleasant for that use case.

**Comment by Boiethios** [comment]
I'll email you. That's not the right place to talk about that 😛
