### ISSUE TITLE
wait_timeout doesn't work as expected

### ISSUE THREAD

**Issue by kanekv** [jonhoo/rust-imap#139]
Documentation suggests (and in fact it will be useful) that `wait_timeout` blocks until new messages appear in inbox or after specified timeout. In fact it calls `wait_inner`.
https://github.com/jonhoo/rust-imap/blob/master/src/extensions/idle.rs#L148

And `wait_inner` in fact catches timeouts and restart itself, so timeouts would end up not stopping it as expected.
https://github.com/jonhoo/rust-imap/blob/master/src/extensions/idle.rs#L97

Is it intentional behavior or you wanted opposite logic in there?
@jonhoo

**Comment by jonhoo** [comment]
Ah, interesting, that is a good catch! You're right -- we would want `wait_inner` to not restart the connection on a timeout if `wait_timeout` was used (it should still do so in other cases where it gets `TimedOut` though. I'd be happy to review a PR!

**Comment by dario23** [comment]
should this be closed, now that #159 is merged?

**Comment by jonhoo** [comment]
@dario23 Ah, yes, good catch, thanks!
