### ISSUE TITLE
measuring imap in/out traffic?

### ISSUE THREAD

**Issue by hpk42** [jonhoo/rust-imap#142]
We are soon to release new https://delta.chat versions (using the new full-rust dc core, which in turns uses rust-imap)  and we'd soon like to focus on minimizing imap traffic as it helps particular user communities where internet traffic is expensive compared to income, i.e. a 500MB-per-month plans is the achievable economical limit there, and many can not even get that.  Internet leaving the region is often 56KBit but luckily they have e-mail servers within the region that are already used now with DC.  

(How) Is it possible to measure the in/out traffic that rust-imap consumes (say, it constantly measures overall number of requests, and overall in/out network packet size) on each imap connection?    We'd really appreciate such a stats-functionality as it would help us to help those communities.

**Comment by jonhoo** [comment]
I think the best way to go about this would be to write a wrapper around `TcpStream` that implements `Read + Write`, but also logs the number of bytes read and written. That change can happen completely independently from `imap`, and then you just use that alternative stream through `imap::Client::new` :)

**Comment by hpk42** [comment]
thanks, makes sense :)
