### ISSUE TITLE
Reaching Jon :)

### ISSUE THREAD

**Issue by hpk42** [jonhoo/rust-imap#143]
hey jon -- i wrote you a mail to the e-mail address at the thesquareplanet -- did it pass spam filters?  Sorry i didn't find another way to double-check ;)

**Comment by jonhoo** [comment]
Hi! Sorry, yes, I got the e-mail. My parents are in town, so haven't had a chance to respond to it yet. It's on my queue :)

**Comment by hpk42** [comment]
On Tue, Sep 24, 2019 at 16:19 -0700, Jon Gjengset wrote:
> Closed #143.

fine -- and sorry for disturbing here -- a common issue
with first-time emails is that they might never make it to human eyes ...
