### ISSUE TITLE
IDLE example

### ISSUE THREAD

**Issue by Lem** [jonhoo/rust-imap#152]
I'm fairly new to rust and would like to learn it by writing something with IMAP.

As I would like to use IDLE, too, I wanted to ask if its possible to add an example on how to use that extension.

**Comment by hpk42** [comment]
you could look at this unmerged PR where i provided an 
working IDLE example: 

https://github.com/jonhoo/rust-imap/pull/148/

maybe you could take up the PR and finish it? :) 

In my project we were in need of manually interruptible IDLE
which is hard to do cross-platform (you need to write some bytes
to the FD on which IDLE is blocking -- or you need to use an
async stack).

**Comment by jonhoo** [comment]
Fixed by #186.
