### ISSUE TITLE
[Suggestion] RFC 5256 - SORT command

### ISSUE THREAD

**Issue by soywod** [jonhoo/rust-imap#178]
It could be nice to implement the `SORT` command from the [RFC 5256](https://tools.ietf.org/html/rfc5256#section-3). Plus it's close to the `SEARCH` command, so it should not be that difficult to integrate.

**Comment by jonhoo** [comment]
I agree, that seems reasonable! Would be happy to take a look at a PR.

**Comment by soywod** [comment]
I'm building an [email CLI client](https://github.com/soywod/himalaya) and I would love this feature to sort messages by date. I will try to implement it ASAP and propose a PR.

**Comment by soywod** [comment]
It seems that the lib `imap-proto` does not have the parser for the `SORT` command, I opened [an issue](https://github.com/djc/tokio-imap/issues/117) there.

**Comment by jonhoo** [comment]
Fixed by #180.

**Comment by soywod** [comment]
@jonhoo I integrated the `v3.0.0-alpha.3` in my tool (mostly to use the sort cmd), and I saw some breaking changes. I noticed that the changelog is not up-to-date, would you like me to update it with the changes I noticed or you prefer to wait for the release `v3.0.0` to list all the breaking changes?

**Comment by jonhoo** [comment]
That'd be great, thank you!

**Comment by soywod** [comment]
Yes, I recognized the format, I also use [the same](https://github.com/soywod/himalaya/blob/master/CHANGELOG.md) :wink:

**Comment by soywod** [comment]
https://github.com/jonhoo/rust-imap/pull/199
