### ISSUE TITLE
README has inconsistent greenmail version

### ISSUE THREAD

**Issue by comex** [jonhoo/rust-imap#187]
From `README.tpl`:
> ```console
> $ docker pull greenmail/standalone:1.6.2
> $ docker run -t -i -e GREENMAIL_OPTS='-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose' -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995 greenmail/standalone:1.5.9
> ```

This has version `1.6.2` on the first line and `1.5.9` on the second line.  I'm not too familiar with Docker, but this seems unlikely to be intended.

**Comment by jonhoo** [comment]
Good catch! Fixed, thank you :)
