### ISSUE TITLE
Missing "References:" field in envelope?

### ISSUE THREAD

**Issue by TornaxO7** [jonhoo/rust-imap#209]
Hi! According to the [RFC5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4) there should be a `References:` field. But the [`imap::types::Fetch.envelope()`](https://docs.rs/imap/3.0.0-alpha.4/imap/types/struct.Fetch.html#method.envelope) function returns an [`envelope`](https://docs.rs/imap-proto/0.14.1/imap_proto/types/struct.Envelope.html) which doesn't include this field (and is not from the latest version?). Can I help here? I don't know where to call this issue, so if you think, that it should be rather called on the [`imap_proto`](https://crates.io/crates/imap-proto) crate, then I can do it there as well.

**Comment by jonhoo** [comment]
Hi! Yes, that should be done in `imap_proto` first, and then once it's there we can adopt it in `imap` :)

**Comment by TornaxO7** [comment]
Ok, so currently, I can't do anything (yet?) because the RFC describes the envelope without the `References:` header field (but does it as well!?). I created an [Errata](https://www.rfc-editor.org/errata/eid6637) for this and I think that we have to wait now for a response.
