### ISSUE TITLE
Better error messages for validation errors

### ISSUE THREAD

**Issue by lu-fennell** [jonhoo/rust-imap#215]
Hi. I accidentally added a newline to a password and my program errored-out with the very undescriptive message:

```
Invalid character in input: '\n'
```

resp

```
Validate(ValidateError('\n'))
```

I think a message along the lines of 

```
Invalid character '\n' in argument 'password' of command 'LOGIN userid password'
```

resp

```
Validate(ValidateError { command: "LOGIN userid password", argument: "password", offending_char: '\n' })
```

would be more helpful. 

I could propose a corresponding pull request, if you are interested.

**Comment by lu-fennell** [comment]
I opened a PR with the straightforward approach, for now.

**Comment by lu-fennell** [comment]
> Btw, what do you think about defining commands like this?:
> [...]

I see that `imap-proto` already provides command builders. They also do validation of quoted strings. Any particular reason why `imap` is not using them, or is not providing an API that accepts `imap-proto` commands?

**Comment by jonhoo** [comment]
We had a discussion about whether we should have command builders a while ago, and decided that it only make sense for _some_ commands, and not all. For example, for `select`, it's not clear that a builder _really_ makes sense. I'm also hesitant to _increase_ our re-exporting of `imap-proto` types because it makes us more vulnerable to breaking changes in `imap-proto`.

**Comment by jonhoo** [comment]
Also cc @mordak

**Comment by mordak** [comment]
I don't think it makes sense to re-export the `imap_proto::builders::command` bits. It would be fine to _use_ them internally if they make sense, but presently the failure mode for an invalid character in, say, a password, it [a panic](https://github.com/djc/tokio-imap/blob/af258b643da2907231bd0fb82dd7e6b56343af67/imap-proto/src/builders/command.rs#L58) and a message that you cannot include CR or LF in a quoted string. This isn't much more friendly than what we do now, and the changes in this PR make this crate's error message way more friendly.

I also am not sure if there is a lot of utility in adding builders for a bunch of commands when it is often simpler to just call, say, `client.login(username, password)` and get your `Result` immediately (and if there is an `Err`, it provides a useful description).
