### ISSUE TITLE
Unable to parse status response

### ISSUE THREAD

**Issue by soywod** [jonhoo/rust-imap#220]
Some of [himalaya](https://github.com/soywod/himalaya/issues/269) users reported me this error while trying to display their messages. The error occurs there:

```rust
let fetches = self
    .sess()?
    .fetch(&range, "(ENVELOPE FLAGS INTERNALDATE)")
    .context(format!(r#"cannot fetch messages within range "{}""#, range))?;
```

It looks like the response from the IMAP server cannot be parsed properly. The problem is that:

1. I cannot reproduce their error (it looks like it fails in a specific context)
2. I cannot see which response fails because it is not included in the final error message:
https://github.com/jonhoo/rust-imap/blob/6808dfef79e26945366794dc16e66cc0ad3d2a15/src/error.rs#L229

Any idea?

**Comment by jonhoo** [comment]
Hmm, interesting. We should probably include the invalid content in the error. In the meantime I would offer your users a way to enable imap's debug mode like here:

https://github.com/jonhoo/rust-imap/blob/d8d69a363b510c9ae506f12844661ae3cc4ecb45/examples/idle.rs#L53

Basically, just set `.debug = true` on your `Session`. That should print the underlying traffic to stdout, which can be used to debug further!

**Comment by soywod** [comment]
Thanks for the tip, I will activate them and let you know if I have more information for you!

**Comment by soywod** [comment]
Someone was able to reproduce the issue with `debug` enabled, it looks like the mailbox cannot be found:

```
C: a2 SELECT "INBOX"
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Forwarded $MailFlagBit0 $NotJunk $NotPhishing $Phishing $has_cal LoadRemoteImages Mail Networking NotJunk OIB-Seen- OIB-Seen-INBOX OIB-Seen-OIB/Business OIB-Seen-OIB/Entertainment OIB-Seen-OIB/Finance OIB-Seen-OIB/Groups OIB-Seen-OIB/Home OIB-Seen-OIB/Jobs OIB-Seen-OIB/Shopping OIB-Seen-OIB/Social OIB-Seen-OIB/Social Networking OIB-Seen-[Gmail]/All Mail OIB-Seen-[Gmail]/Important OIB-Seen-[Gmail]/Spam OIB-Seen-[Gmail]/Trash Old receipt-handled)
Error: cannot select mailbox INBOX
```

But when listing mailboxes we can see the `INBOX` one:

```
C: a2 LIST "" *
S: * LIST (\HasNoChildren) "/" "Archive"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: * LIST (\HasChildren \Noselect) "/" "[Gmail]"
S: * LIST (\Drafts \HasNoChildren) "/" "[Gmail]/Drafts"
S: * LIST (\HasNoChildren \Important) "/" "[Gmail]/Important"
S: * LIST (\HasNoChildren \Sent) "/" "[Gmail]/Sent Mail"
S: * LIST (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
S: * LIST (\Flagged \HasNoChildren) "/" "[Gmail]/Starred"
S: * LIST (\HasNoChildren \Trash) "/" "[Gmail]/Trash"
S: a2 OK Success
```

Any idea?

**Comment by jonhoo** [comment]
Hmm, that's interesting — do they not get an `a2 OK` in that first response? That makes it seem as though the server _just_ sends the flags but doesn't confirm the operation. If there is an OK hiding there, then I wonder if we fail to parse the `FLAGS` line somehow. Could you try adding that whole line into a unit test and see that it parses without error (maybe even just directly parse it with `imap_proto`)?

**Comment by soywod** [comment]
Sorry for the delay! I added this test:

```rust
    #[test]
    fn parse_bad_mailbox() {
        let lines = b"* FLAGS (\\Answered \\Flagged \\Draft \\Deleted \\Seen $Forwarded $MailFlagBit0 $NotJunk $NotPhishing $Phishing $has_cal LoadRemoteImages Mail Networking NotJunk OIB-Seen- OIB-Seen-INBOX OIB-Seen-OIB/Business OIB-Seen-OIB/Entertainment OIB-Seen-OIB/Finance OIB-Seen-OIB/Groups OIB-Seen-OIB/Home OIB-Seen-OIB/Jobs OIB-Seen-OIB/Shopping OIB-Seen-OIB/Social OIB-Seen-OIB/Social Networking OIB-Seen-[Gmail]/All Mail OIB-Seen-[Gmail]/Important OIB-Seen-[Gmail]/Spam OIB-Seen-[Gmail]/Trash Old receipt-handled)\r\n";
        let (mut send, recv) = mpsc::channel();
        parse_mailbox(lines, &mut send).unwrap();
        assert!(recv.try_recv().is_err());
    }
```

And I got this error:

```rust
// thread 'parse::tests::parse_bad_mailbox' panicked at 'called `Result::unwrap()` on an `Err` value: Parse(Invalid([42, 32, 70, …]))', src/parse.rs:571:41
```

When I log the sub error I have this:

```rust
// err: Error(Error { input: [42, 32, 70, …], code: TakeWhile1 })
```

**Comment by soywod** [comment]
After narrowing the string, it looks like the issue comes from the brackets `OIB-Seen-[Gmail]` :thinking:

**Comment by soywod** [comment]
More specifically the closing bracket: https://github.com/djc/tokio-imap/blob/a3231eb61d71d6c841c3d88796332c25034aafa1/imap-proto/src/parser/core.rs#L151-L154

**Comment by jonhoo** [comment]
I'm curious what @djc (the maintainer of `imap-proto`) has to say here.

**Comment by djc** [comment]
Seems to be a duplicate of https://github.com/djc/tokio-imap/issues/36, see also things like https://bugs.python.org/issue21815 and https://github.com/jstedfast/MailKit/issues/193. It this point probably make sense to just allow `[` and `]` in flags, I'd open to taking a patch for this in imap-proto. Would be really nice to figure out where this OIB-Seen crap comes from...

**Comment by soywod** [comment]
The PR has been merged, let me know when a new release is available :slightly_smiling_face:

**Comment by djc** [comment]
imap-proto 0.16.2 is on crates.io now.

**Comment by soywod** [comment]
@jonhoo when could you possibly release a new version? No pressure of course, it is just to know when I will be able to release mine :slightly_smiling_face:

**Comment by jonhoo** [comment]
@soywod I'm not sure what you mean? Given that all that's needed here is the newer version of `imap-proto`, and they did a point release, you should be able to get the fix just by doing `cargo update`. No new version of `imap` should be necessary.

**Comment by soywod** [comment]
@jonhoo I need a new version because I am using `rust-imap`, not `imap-proto` directly.

**Comment by soywod** [comment]
I mean, if I do not mistake, `rust-imap` needs to update `imap-proto` version so the fix can be accessible, right?

**Comment by jonhoo** [comment]
Nope, that shouldn't be necessary since `imap` specifies `imap-proto = "0.16.1"`, which is compatible with `0.16.2` (which contains the fix).

**Comment by soywod** [comment]
> Nope, that shouldn't be necessary since `imap` specifies `imap-proto =
> "0.16.1"`, which is compatible with `0.16.2` (which contains the fix).

Oh great, I may have mistaken something. Sorry then!
