### ISSUE TITLE
Publish cyrus-imapd-tester Dockerfile

### ISSUE THREAD

**Issue by bitfehler** [jonhoo/rust-imap#239]
Hey there,

I promise I won't be dogmatic about it, but I did want to give it try :slightly_smiling_face: I tried to find the Dockerfile used to build the cyrus-imapd-tester container used for the integration tests, but could not find it. I was wondering if it could maybe be published either here or wherever? Would be great both for understanding how  it works and also for potentially suggesting improvements. Thanks a lot! :green_heart: 

If I understand correctly, this one is probably for @urkle

**Comment by urkle** [comment]
@bitfehler no problem.. I've published a repo with the build sources.  (and linked it on docker hub as well ) https://github.com/OutOfOrder/containers/tree/master/cyrus-imap-tester

**Comment by bitfehler** [comment]
Thank you so much, @urkle! It's super useful for testing some of the more advanced features :sparkling_heart:
