### ISSUE TITLE
Add support for IMAP's `NOTIFY` extension. (RFC 5465)

### ISSUE THREAD

**Issue by maltalef101** [jonhoo/rust-imap#246]
[This](https://www.rfc-editor.org/rfc/rfc5465.html) extension allows the server to send unsolicited responses of certain events set by the client. I don't know how this would be implemented, but with some guiding I think I could give it a try. I'm not a Rustacean by trait but I am willing to sharpen my Rust sword.

**Comment by jonhoo** [comment]
There's some more context in https://github.com/jonhoo/rust-imap/issues/63 (I'll close this in favor of that) and https://github.com/mattnenterprise/rust-imap/issues/63. Maybe @jkaessens is still up for helping out too? I'd definitely love to take a look at a PR!
