### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by JasterV** [jonhoo/rust-imap#258]
Hello there:) This is more a question than an issue.

Is it possible to read the attachments of an email? Since IMAP protocol supports it I was wondering if this library can also handle that, otherwise I could try to contribute :)

Thank you rocket

**Comment by jonhoo** [comment]
Hey! You should be able to grab any part of the body (including attachments) through the use of `Session::fetch` and then inspecting the resulting `Fetch` responses. The attachments will generally be outlined in the "bodystructure" part of `Fetch`, which you can then fetch explicitly later on using `BODY`. [This StackOverflow answer](https://stackoverflow.com/questions/4745572/imap-attachment-retrieving-command) has some pointers that may prove useful :)
