### ISSUE TITLE
Discarded EXPUNGE/EXISTS responses

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/rust-imap#72]
> When the wait functions return on an `IdleHandle`, the response doesn't contain the list of untagged EXPUNGE and EXISTS responses that have occurred. This means we don't necessarily know which sequence ids correspond to which messages anymore. E.g, we may be able to determine that a message was deleted because the `exists` parameter on the mailbox was decremented, but we don't know if that was the message with sequence id 1 or 10,000. This means that we have to maintain a record of the UID list and run unnecessary UID searches sometimes.
>
> The wait functions currently return a Result<()>. They could be updated to return a list of EXPUNGE and EXISTS responses.

See the original issue here: https://github.com/mattnenterprise/rust-imap/issues/72

**Comment by jonhoo** [comment]
I think this is perhaps now solved with #186 @mordak?

**Comment by mordak** [comment]
> I think this is perhaps now solved with #186 @mordak?

I think so. If the caller wants the responses then they can get them. EXPUNGE and EXISTS are available.
